/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as GalleryIndexRouteImport } from './routes/gallery.index'
import { Route as DonateIndexRouteImport } from './routes/donate.index'
import { Route as ContactIndexRouteImport } from './routes/contact.index'
import { Route as ActivitiesIndexRouteImport } from './routes/activities.index'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ActivitiesSlugRouteImport } from './routes/activities.$slug'
import { Route as AdminProgramsRouteImport } from './routes/_admin.programs'
import { Route as AdminGalleryRouteImport } from './routes/_admin.gallery'
import { Route as AdminDashboardRouteImport } from './routes/_admin.dashboard'
import { Route as AdminActivitiesRouteImport } from './routes/_admin.activities'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateIndexRoute = DonateIndexRouteImport.update({
  id: '/donate/',
  path: '/donate/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesIndexRoute = ActivitiesIndexRouteImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesSlugRoute = ActivitiesSlugRouteImport.update({
  id: '/activities/$slug',
  path: '/activities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivitiesRoute = AdminActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof AdminActivitiesRoute
  '/dashboard': typeof AdminDashboardRoute
  '/gallery': typeof AdminGalleryRoute
  '/programs': typeof AdminProgramsRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/admin/login': typeof AdminLoginRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/activities/': typeof ActivitiesIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/donate/': typeof DonateIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesIndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/gallery': typeof GalleryIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/admin/login': typeof AdminLoginRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/contact': typeof ContactIndexRoute
  '/donate': typeof DonateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/about': typeof AboutRoute
  '/_admin/activities': typeof AdminActivitiesRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/gallery': typeof AdminGalleryRoute
  '/_admin/programs': typeof AdminProgramsRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/admin/login': typeof AdminLoginRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/activities/': typeof ActivitiesIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/donate/': typeof DonateIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activities'
    | '/dashboard'
    | '/gallery'
    | '/programs'
    | '/activities/$slug'
    | '/admin/login'
    | '/programs/$slug'
    | '/activities/'
    | '/contact/'
    | '/donate/'
    | '/gallery/'
    | '/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activities'
    | '/dashboard'
    | '/gallery'
    | '/programs'
    | '/activities/$slug'
    | '/admin/login'
    | '/programs/$slug'
    | '/contact'
    | '/donate'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/about'
    | '/_admin/activities'
    | '/_admin/dashboard'
    | '/_admin/gallery'
    | '/_admin/programs'
    | '/activities/$slug'
    | '/admin/login'
    | '/programs/$slug'
    | '/activities/'
    | '/contact/'
    | '/donate/'
    | '/gallery/'
    | '/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AboutRoute: typeof AboutRoute
  ActivitiesSlugRoute: typeof ActivitiesSlugRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  ActivitiesIndexRoute: typeof ActivitiesIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  DonateIndexRoute: typeof DonateIndexRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/': {
      id: '/donate/'
      path: '/donate'
      fullPath: '/donate/'
      preLoaderRoute: typeof DonateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/': {
      id: '/activities/'
      path: '/activities'
      fullPath: '/activities/'
      preLoaderRoute: typeof ActivitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/$slug': {
      id: '/activities/$slug'
      path: '/activities/$slug'
      fullPath: '/activities/$slug'
      preLoaderRoute: typeof ActivitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/programs': {
      id: '/_admin/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/gallery': {
      id: '/_admin/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/activities': {
      id: '/_admin/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AdminActivitiesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivitiesRoute: typeof AdminActivitiesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivitiesRoute: AdminActivitiesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminProgramsRoute: AdminProgramsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AboutRoute: AboutRoute,
  ActivitiesSlugRoute: ActivitiesSlugRoute,
  AdminLoginRoute: AdminLoginRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  ActivitiesIndexRoute: ActivitiesIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  DonateIndexRoute: DonateIndexRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
